### ISSUE TITLE
error  _ModuleNotFoundError: No module named 'data_handlers'_

### ISSUE THREAD

**Issue by jiminbot20** [lukewys/dcase_2020_T6#1]
During running instruction 

**Run main.py to create dataset and extract features under current directory. Result folders would be data_splits, data_splits_audio and pickles.**

occurs error 
_ModuleNotFoundError: No module named 'data_handlers'_
 
I think 'data_handling' should be changed to 'data_handlers'

**Comment by jiminbot20** [comment]
also error occurs even after change like above
_ModuleNotFoundError: No module named 'data_handlers.clotho_loader'_

In this error, I think 'clotho_data_loader.py' should be changed into 'clotho_loader.py'

**Comment by jiminbot20** [comment]
also audio is not splitting is not working I think this would be also naming problem.

FileNotFoundError: [Errno 2] No such file or directory: 'data/data_splits_audio/development'

confusing between 'data_splits_audio' and 'data_splits'

**Comment by jiminbot20** [comment]
**Then, run creat_test_set.py to create test set under current directory. Result folder would be test_data.**

this part also doesn't work. 
_Create test data in multiprocess:
0it [00:00, ?it/s]
Test data created._
after running this code, there is no any wav file in 'clotho_test_audio' folder

**Comment by lukewys** [comment]
Hi @jiminbot20, please find the newest update where I fixed the error. Very sorry about that. The naming of 'data_splits_audio' and 'data_splits' is used in the official code of clotho dataset, where 'data_splits_audio' means the data containing raw audio, and data_splits means the data with spectrograms. Also please find a updated ReadME where you need to setup coco_caption before run the trianing.

**Comment by jiminbot20** [comment]
Thank you for quick reply. I am currently studying all audio captioning DCASE2020 winning studies. Your study is a huge help to me.

**Comment by lukewys** [comment]
No problem. Thank you for your interested in our study. I'm closing this issue.
