### ISSUE TITLE
I could not TEST!

### ISSUE THREAD

**Issue by jiminbot20** [lukewys/dcase_2020_T6#4]
After I train and evaluate, I tried to test but I couldn't. Because test data do not create. 'clotho_test_audio' is not appearing even I run the code below
![image](https://user-images.githubusercontent.com/63258184/93861888-333fd180-fcfc-11ea-9b25-9f4de60b8183.png)
only those folders are exist.
![image](https://user-images.githubusercontent.com/63258184/93861946-4b175580-fcfc-11ea-96e1-94078b1b89f5.png)
Please help. Thx

**Comment by lukewys** [comment]
Hi, did you download the test data and name the test data as clotho_test_audio? As in the readme:

data
├── clotho_csv_files
│   ├── clotho_captions_development.csv
│   ├── clotho_captions_evaluation.csv
│   ├── clotho_metadata_development.csv
│   └── clotho_metadata_evaluation.csv
├── clotho_audio_files
│   ├── development
│   └── evaluation
└── clotho_test_audio

download link: http://dcase.community/challenge2020/task-automatic-audio-captioning#download

P.S. I found that there is a typo in create_test_set.py. I am fixing that.

**Comment by jiminbot20** [comment]
Oh...I didn't. Sorry for my mistake

Android용 Outlook<https://aka.ms/ghei36> 다운로드

________________________________
