### ISSUE TITLE
how to get 'test_out.csv'?

### ISSUE THREAD

**Issue by jiminbot20** [lukewys/dcase_2020_T6#5]
I downloaded 'clotho_audio_test' and changed 'hparam.py' mode = 'test'
Then, I run **python train.py**
'test_out.csv' was created but it was empty.
I was expecting 
![image](https://user-images.githubusercontent.com/63258184/93972359-157e7500-fdad-11ea-9380-7cb6bd01c586.png)
But it was
![image](https://user-images.githubusercontent.com/63258184/93972375-23cc9100-fdad-11ea-99e8-f683e048983a.png)
like this. 
How can I get proper 'test_out.csv' and scores of the test?

This is capture of terminal after I run the code.
![image](https://user-images.githubusercontent.com/63258184/93972690-b836f380-fdad-11ea-8110-6c3a0aef2e18.png)

**Comment by Chen-Kun** [comment]
Are there corresponding .npy files in your **data/test_data** directory? If not, you should enter the create_dataset directory,  and run **python create_test_set.py** to prepare the data.

**Comment by jiminbot20** [comment]
If directory should be **data/test_data**, then directory down below is wrong?
![image](https://user-images.githubusercontent.com/63258184/93985096-95add600-fdbf-11ea-9902-4a155d49b0cc.png)

**Comment by Chen-Kun** [comment]
It is correct. The model does not use audio as input, but the corresponding Mel-spectrogram. So we need to extract the data and save the results in the corresponding folder.  The  data/test_data  is obtained by **create_test_set.py**

**Comment by jiminbot20** [comment]
![image](https://user-images.githubusercontent.com/63258184/93986419-4c5e8600-fdc1-11ea-8f90-a7ce15a62e9b.png)
Still not working...after I run the code it ends so quick and **test_data** folder is not creating

**Comment by lukewys** [comment]
Hi @jiminbot20 , does the clotho_test_audio contains the evaluation set audio? It should be the folder extracted from clotho_audio_test.7z. I tried on my own yesterday, it works fine.

**Comment by Chen-Kun** [comment]
I tried to run it, and there is no problem.
![image](https://user-images.githubusercontent.com/25267283/93987253-e91d2580-fdb9-11ea-9c86-f2820d01136c.png)
The problem may be that the code does not find the clotho_test_audio directory. My **data** directory is in the **create_dataset** directory. You can modify line 46 of **create_test_set.py** according to the location of your data.

**Comment by jiminbot20** [comment]
clotho_audio_test looks like this
![image](https://user-images.githubusercontent.com/63258184/93988309-829d0500-fdc3-11ea-89fc-0b2f1ff9eb1a.png)
And zip file that I downloaded is like this
![image](https://user-images.githubusercontent.com/63258184/93988435-a7917800-fdc3-11ea-8a50-d8a69a495e3b.png)

Is this right?

**Comment by lukewys** [comment]
No,  it should contain directly the *.wav files. In other words, you don't need the test folder.

**Comment by Chen-Kun** [comment]
![image](https://user-images.githubusercontent.com/25267283/93988807-bd9b3a80-fdbb-11ea-9634-1794047d0739.png)
Should be like this.

**Comment by jiminbot20** [comment]
Oh I figure out. path problem...
line 46 'creat_test_set.py' in your git is written as '_file_list = glob.glob('./data/clotho_test_audio/*.wav')_'
but it should be change into '_file_list = glob.glob('./data/clotho_audio_test/test/*.wav')'_

**Comment by lukewys** [comment]
Yes, in default we do not expect the "test" folder. You could change it to whatever you like.

**Comment by jiminbot20** [comment]
![image](https://user-images.githubusercontent.com/63258184/94005758-b4b96180-fdd9-11ea-8e78-50153741c905.png)
I did it! Thanks for helping me!
